spring:
  application:
    name: yu-ai-code-mother-backend
      # mysql
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/su_ai_code
      username: root
      password: root

  profiles:
    active: local

server:
  port: 8123
  servlet:
    context-path: /api

springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.example.aicodesu.controller

knife4j:
  enable: true
  setting:
    language: zh_cn
